# Generated by Django 4.0.6 on 2022-07-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('amount', models.IntegerField(default=1000)),
                ('account_no', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TrasactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.IntegerField(blank=True, default=0)),
                ('credit_amount', models.IntegerField(blank=True, default=0)),
                ('to_acc', models.IntegerField(blank=True, null=True)),
                ('closing_balance', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=25)),
                ('acc_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bankapp.createaccount')),
            ],
        ),
        migrations.AddField(
            model_name='createaccount',
            name='Register',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bankapp.register'),
        ),
    ]
