# Generated by Django 4.0.6 on 2022-07-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createaccount',
            old_name='amount',
            new_name='initial_amount',
        ),
    ]
