# Generated by Django 4.0.6 on 2022-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0002_rename_amount_createaccount_initial_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasactiondetails',
            name='to_acc',
            field=models.IntegerField(blank=True, default='self', null=True),
        ),
    ]
