# Generated by Django 4.0.6 on 2022-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0003_alter_trasactiondetails_to_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasactiondetails',
            name='to_acc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
