# Generated by Django 4.0.6 on 2022-08-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0004_alter_trasactiondetails_to_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccount',
            name='rec_acc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
